#!/bin/sh

if [[ ! -d "/ngrok/ssl" || "`ls -A /ngrok/ssl`" == "" ]]; then
    mkdir -p /ngrok/ssl && cd /ngrok/ssl
    openssl genrsa -out rootCA.key 2048
    openssl req -x509 -new -nodes -key rootCA.key -subj "/CN=$HOSTNAME" -days 5000 -out rootCA.pem
    openssl genrsa -out device.key 2048
    openssl req -new -key device.key -subj "/CN=$HOSTNAME" -out device.csr
    openssl x509 -req -in device.csr -CA rootCA.pem -CAkey rootCA.key -CAcreateserial -out device.crt -days 5000
fi

cp /ngrok/ssl/rootCA.pem /ngrok/assets/client/tls/ngrokroot.crt -f
cp /ngrok/ssl/device.crt /ngrok/assets/server/tls/snakeoil.crt -f
cp /ngrok/ssl/device.key /ngrok/assets/server/tls/snakeoil.key -f

cd /ngrok

make release-server

sed -i "s/ngrokd.ngrok.com:443/$HOSTNAME:4443/g" /ngrok/src/ngrok/client/model.go

GOOS=windows GOARCH=amd64 make release-client

/ngrok/bin/ngrokd -domain=$HOSTNAME -httpAddr=":80"