#!/bin/sh

cp /ngrok/ssl/ngrokroot.crt /ngrok/assets/client/tls/ngrokroot.crt -f
cp /ngrok/ssl/snakeoil.crt /ngrok/assets/server/tls/snakeoil.crt -f
cp /ngrok/ssl/snakeoil.key /ngrok/assets/server/tls/snakeoil.key -f

cd /ngrok

make release-server

sed -i "s/ngrokd.ngrok.com:443/$HOSTNAME:4443/g" /ngrok/src/ngrok/client/model.go

GOOS=windows GOARCH=amd64 make release-client

/ngrok/bin/ngrokd -domain=$HOSTNAME -httpAddr=":80"